In [8]:
import pandas as pd

data = pd.read_csv("C:\\Users\\Person\\Desktop\\Python_resources\\merito-analiza-danych-cwiczenia\\dane\\real_GDP_per_capita.csv")
print(data.head())

   #  geo\TIME_PERIOD  AT: Austria  BE: Belgium  BG: Bulgaria  CY: Cyprus  \
0  1             1995        30290        28400          3630       17530
1  2             1996        30920        28720          3840       17470
2  3             1997        31540        29740          3320       17680
3  4             1998        32610        30260          3460       18530
4  5             1999        33770        31250          3190       19240

   CZ: Czech Republic  DE: Germany  DK: Denmark  \
0               10320        28960        39110
1               10770        29210        39990
2               10720        29730        41080
3               10690        30380        41900
4               10850        31040        43000

   EA20: Euro Area (the 20 countries using the euro)  ...  LU: Luxembourg  \
0                                              24610  ...           67360
1                                              24980  ...           67480
2                                              25590  ...           70230
3                                              26300  ...           73970
4                                              27030  ...           78880

   LV: Latvia  MT: Malta  NL: Netherlands  PL: Poland  PT: Portugal  \
0        4200          0            30570        5150         14250
1        4350          0            31470        5460         14700
2        4790          0            32640        5810         15270
3        5160          0            33940        6080         15930
4        5340          0            35420        6370         16460

   RO: Romania  SE: Sweden  SI: Slovenia  SK: Slovakia
0         4120       31610         11980          6990
1         4300       32100         12320          7400
2         4100       33070         12980          7790
3         4020       34460         13400          8080
4         4020       35880         14100          8040

[5 rows x 31 columns]

In [9]:
print(data.describe())

               #  geo\TIME_PERIOD   AT: Austria   BE: Belgium  BG: Bulgaria  \
count  29.000000        29.000000     29.000000     29.000000     29.000000
mean   15.000000      2009.000000  37724.827586  35096.551724   5593.793103
std     8.514693         8.514693   3447.035601   3224.204526   1743.916802
min     1.000000      1995.000000  30290.000000  28400.000000   3190.000000
25%     8.000000      2002.000000  35430.000000  32990.000000   3840.000000
50%    15.000000      2009.000000  39140.000000  36060.000000   5690.000000
75%    22.000000      2016.000000  39870.000000  36860.000000   6840.000000
max    29.000000      2023.000000  42540.000000  40370.000000   8850.000000

         CY: Cyprus  CZ: Czech Republic   DE: Germany   DK: Denmark  \
count     29.000000           29.000000     29.000000     29.000000
mean   22523.793103        14560.689655  35088.965517  47065.172414
std     3066.614482         2742.175793   3528.189889   4023.548204
min    17470.000000        10320.000000  28960.000000  39110.000000
25%    20490.000000        11880.000000  32320.000000  44770.000000
50%    22460.000000        15130.000000  35360.000000  46890.000000
75%    24480.000000        16640.000000  38180.000000  48970.000000
max    29150.000000        18570.000000  39840.000000  55280.000000

       EA20: Euro Area (the 20 countries using the euro)  ...  LU: Luxembourg  \
count                                          29.000000  ...       29.000000
mean                                        29970.000000  ...    90158.275862
std                                          2567.838168  ...     9738.415121
min                                         24610.000000  ...    67360.000000
25%                                         28640.000000  ...    86680.000000
50%                                         30280.000000  ...    94600.000000
75%                                         31220.000000  ...    95920.000000
max                                         34190.000000  ...   101170.000000

         LV: Latvia     MT: Malta  NL: Netherlands    PL: Poland  \
count     29.000000     29.000000        29.000000     29.000000
mean    9829.655172  17255.517241     39527.241379   9658.620690
std     3418.064911   9110.358150      4134.497634   3105.647763
min     4200.000000      0.000000     30570.000000   5150.000000
25%     6710.000000  15640.000000     37080.000000   6880.000000
50%    10370.000000  18080.000000     40230.000000   9330.000000
75%    12430.000000  23400.000000     42050.000000  11740.000000
max    15020.000000  29500.000000     46670.000000  15280.000000

       PT: Portugal   RO: Romania    SE: Sweden  SI: Slovenia  SK: Slovakia
count     29.000000     29.000000     29.000000     29.000000     29.000000
mean   17376.206897   6963.448276  42247.586207  17773.793103  12227.241379
std     1313.491568   2316.543416   5242.584324   3121.623220   3406.033404
min    14250.000000   4020.000000  31610.000000  11980.000000   6990.000000
25%    16950.000000   4740.000000  38620.000000  15410.000000   8730.000000
50%    17350.000000   7140.000000  43680.000000  18230.000000  13000.000000
75%    18010.000000   8370.000000  46640.000000  19980.000000  15090.000000
max    20090.000000  11170.000000  49300.000000  23170.000000  17240.000000

[8 rows x 31 columns]